version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"   

  api:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/lostandfounddb
      - NODE_ENV=production
      - JWT_SECRET=your_secret_key
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  mongo-data:

