apiVersion: apps/v1
kind: Deployment
metadata:
  name: lostfound-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lostfound-app
  template:
    metadata:
      labels:
        app: lostfound-app
    spec:
      containers:
        - name: lostfound-container
          image: 22i0837/devops_project-api
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_URI
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET
          volumeMounts:
            - name: uploads-volume
              mountPath: /app/uploads
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: uploads-pvc

